### ISSUE TITLE
_plugins/convert.rb:32:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)

### ISSUE THREAD

**Issue by mashdot** [eggcaker/jekyll-org#13]
Seems Jekyll 3.0.0 has broken jekyll-org?

This ```<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)``` error is popping up elsewhere for other people too, but it's not clear what is breaking things.

- https://talk.jekyllrb.com/t/error-messages-when-upgrading-to-3-0-on-mac-os-x/1398/4
- https://github.com/jekyll/jekyll/issues/4105

For testing simply a ```jekyll new testing``` with ```jekyll-org``` cloned into ```_plugins```:
```
 ~/testing$ jekyll -v
jekyll 3.0.0
 ~/testing$ jekyll serve
Configuration file: /home/mash/testing/_config.yml
/home/mash/testing/_plugins/convert.rb:32:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
	from /home/mash/testing/_plugins/convert.rb:3:in `<top (required)>'
	from /home/mash/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mash/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /home/mash/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /home/mash/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /home/mash/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /home/mash/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/mash/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mashdot** [comment]
Seems ```jekyll/post``` no longer exists 3.0.0.

- https://github.com/jekyll/jekyll/blob/v2.5.3/lib/jekyll/post.rb

**Comment by mashdot** [comment]
When I get a chance to look at things I will see if I can workout how to fix this.

**Comment by eggcaker** [comment]
cool!

**Comment by mashdot** [comment]
Been playing around today but the whole YAML header thing is a pain! `document.rb` which replaces `post.rb` changes everything. :(
