### ISSUE TITLE
cannot make the page running at all

### ISSUE THREAD

**Issue by test0wanie** [eggcaker/jekyll-org#57]
Hi,

I've followed the instructions precisely as they were written out in the readme so I have `jekyll-org` included both in my `_config.yaml` file and in the `Gemfile`. However it still doesn't seem to work. 

Right now I have only 3 files included with my page: `index.md` and `about.md` (defaults) and the `info.org` file (I've emptied `_posts` directory and it did not change the behaviour) that I've added. It is also worthy mentioning that I am using the `jekyll-katex` plugin but I don't think it's the issue.

My `info.org` file looks like this:
```org
#+LAYOUT: page
#+TITLE: Info
#+PERMALINK: /info/

*** org mode test
testing the ~org~ mode


/voila/.
```
but running `bundle exec jekyll serve --watch --trace` gives this:
```
OrgSite grzegorz$ bundle exec jekyll serve --watch --trace
Configuration file: /Users/grzegorz/programming/OrgSite/_config.yml
Katex Configuration: Found KaTeX js at: /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-katex-1.0.0/lib/assets/js/katex.min.js
Configuration file: /Users/grzegorz/programming/OrgSite/_config.yml
            Source: /Users/grzegorz/programming/OrgSite
       Destination: /Users/grzegorz/programming/OrgSite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/3.0.0/bin/jekyll)
/usr/local/lib/ruby/gems/3.0.0/gems/jekyll-org-1.1.1/lib/jekyll-org.rb:44:in `read': no implicit conversion of Hash into Integer (TypeError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-org-1.1.1/lib/jekyll-org.rb:44:in `read_yaml'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/page.rb:51:in `initialize'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/readers/page_reader.rb:20:in `new'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/readers/page_reader.rb:20:in `block in read'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/readers/page_reader.rb:19:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/readers/page_reader.rb:19:in `read'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/reader.rb:101:in `retrieve_pages'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-org-1.1.1/lib/jekyll-org.rb:76:in `retrieve_org_files'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-org-1.1.1/lib/jekyll-org.rb:83:in `retrieve_static_files'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/reader.rb:62:in `read_directories'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/reader.rb:16:in `read'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:181:in `read'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:78:in `process'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jekyll:23:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jekyll:23:in `<top (required)>'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/cli.rb:494:in `exec'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/cli.rb:30:in `dispatch'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/cli.rb:24:in `start'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/exe/bundle:49:in `block in <top (required)>'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	from /Users/grzegorz/.gem/ruby/3.0.0/gems/bundler-2.2.9/exe/bundle:37:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:23:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/bundle:23:in `<main>'
```
so yeah. It doesn't work. Searching for similar tracebacks wasn't helpful as well.

versions:
`jekyll 4.2.0` and `jekyll-org 1.1.1`

All files are pretty much the defaults from `jekyll new` apart from adding KaTeX (which works on my markdown jekyll page)

**Comment by disconsis** [comment]
Seems like this [commit](https://github.com/eggcaker/jekyll-org/commit/cadd906bbb213551956c366a02586f143708ba37) fixes it. This needs a major version bump as both v1.1.0 and v1.1.1 are failing with ruby 3.0.1
@ggegoge I'd recommend using it as a submodule - I think the docs show how to do that somewhere.

**Comment by laniusone** [comment]
I know it is a little necro-posting, but you can use the master branch in your `Gemfile`, and the plugin seems to work then.

```
gem 'jekyll-org', git: 'git@github.com:eggcaker/jekyll-org.git', branch: 'master'
```
